slides: !!python/tuple
- /home/satyaprakash/WSI/TCGA-CF-A5UA-01Z-00-DX1.7352D4EB-46F5-4EAA-95B9-1D869E8291C3.svs
verbose: 1
export_dir: ./wsi_output/
batch_size: 12
n_workers: 5
tile_size: 224
n_tiles: null
